// AI Model configurations
import { Model } from '../../types';

export const MODELS: Model[] = [
  {
    id: 'qwen2.5:3b',
    name: 'Qwen 2.5 3B (Local)',
    icon: '🐼',
    description: 'Fast & efficient local model',
    provider: 'ollama',
    baseUrl: '/api/ollama',
    requiresToken: false,
    category: 'Fast',
    shortName: 'Qwen',
  },
  {
    id: 'ministral-3b',
    name: 'Ministral 3B',
    icon: '💨',
    description: 'Edge-optimized model, fast and efficient',
    provider: 'github',
    baseUrl: 'https://models.inference.ai.azure.com',
    requiresToken: true,
    category: 'Fast',
    shortName: 'Ministral',
  },
  {
    id: 'deepseek-r1:7b',
    name: 'DeepSeek R1 7B (Local)',
    icon: '🧠',
    description: 'Reasoning model with thinking',
    provider: 'ollama',
    baseUrl: '/api/ollama',
    requiresToken: false,
    category: 'Thinking',
    shortName: 'R1 7B',
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    icon: '🤖',
    description: 'Most capable model, best for complex tasks',
    provider: 'github',
    baseUrl: 'https://models.inference.ai.azure.com',
    requiresToken: true,
    category: 'Pro',
    shortName: 'GPT-4o',
  },
  {
    id: 'gemma4',
    name: 'Gemma 4 (Local)',
    icon: '🔥',
    description: 'High-performance open model from Google',
    provider: 'ollama',
    baseUrl: '/api/ollama',
    requiresToken: false,
    category: 'Pro',
    shortName: 'Gemma 4',
  },
  {
    id: 'gemma4:e2b',
    name: 'Gemma 4 E2B (Local)',
    icon: '⚡',
    description: 'Lightweight Gemma 4 variant, faster inference',
    provider: 'ollama',
    baseUrl: '/api/ollama',
    requiresToken: false,
    category: 'Fast',
    shortName: 'Gemma 4 E2B',
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    icon: '✨',
    description: "Google's fast multimodal model",
    provider: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    requiresToken: true,
    category: 'Pro',
    shortName: 'Gemini',
  },
  {
    id: 'gemini-3.5-flash-lite',
    name: 'Gemini 3.5 Flash Lite',
    icon: '🍃',
    description: "Google's ultra-light, low-cost model",
    provider: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    requiresToken: true,
    category: 'Fast',
    shortName: 'Flash Lite',
  },
  {
    id: 'gemini-3.7-flash',
    name: 'Gemini 3.7 Flash',
    icon: '🌟',
    description: "Google's latest fast multimodal model",
    provider: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    requiresToken: true,
    category: 'Fast',
    shortName: 'Flash 3.7',
  },
  {
    id: 'gemini-3.1-pro-preview',
    name: 'Gemini 3.1 Pro Preview',
    icon: '🔮',
    description: "Google's most capable model (preview)",
    provider: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    requiresToken: true,
    category: 'Pro',
    shortName: 'Pro Preview',
  },
  {
    id: 'claude-haiku-4-5-20251001',
    name: 'Claude Haiku 4.5',
    icon: '🐰',
    description: 'Fast and compact model for quick responses',
    provider: 'anthropic',
    requiresToken: true,
    category: 'Fast',
    shortName: 'Haiku',
  },
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    icon: '🎵',
    description: 'Balanced model with excellent reasoning',
    provider: 'anthropic',
    requiresToken: true,
    category: 'Pro',
    shortName: 'Sonnet',
  },
  {
    id: 'claude-opus-4-7',
    name: 'Claude Opus 4.7',
    icon: '🎭',
    description: 'Most capable model with advanced reasoning',
    provider: 'anthropic',
    requiresToken: true,
    category: 'Thinking',
    shortName: 'Opus',
  },
  {
    id: 'gpt-5.6-luna',
    name: 'GPT-5.6 Luna',
    icon: '🌙',
    description: "OpenAI's fast, lightweight model",
    provider: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    requiresToken: true,
    category: 'Fast',
    shortName: 'Luna',
  },
  {
    id: 'gpt-5.6-sol',
    name: 'GPT-5.6 Sol',
    icon: '☀️',
    description: "OpenAI's most capable model",
    provider: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    requiresToken: true,
    category: 'Pro',
    shortName: 'Sol',
  },
];
