// AI Model configurations
import { Model } from '../../types';

export const MODELS: Model[] = [
  {
    id: 'qwen2.5:3b',
    name: 'Qwen 2.5 3B (Local)',
    icon: '🐼',
    description: 'Fast & efficient local model',
    provider: 'ollama',
    baseUrl: '/api/ollama',
    requiresToken: false,
    category: 'Fast',
    shortName: 'Qwen',
  },
  {
    id: 'ministral-3b',
    name: 'Ministral 3B',
    icon: '💨',
    description: 'Edge-optimized model, fast and efficient',
    provider: 'github',
    baseUrl: 'https://models.inference.ai.azure.com',
    requiresToken: true,
    category: 'Fast',
    shortName: 'Ministral',
  },
  {
    id: 'deepseek-r1:7b',
    name: 'DeepSeek R1 7B (Local)',
    icon: '🧠',
    description: 'Reasoning model with thinking',
    provider: 'ollama',
    baseUrl: '/api/ollama',
    requiresToken: false,
    category: 'Thinking',
    shortName: 'R1 7B',
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    icon: '🤖',
    description: 'Most capable model, best for complex tasks',
    provider: 'github',
    baseUrl: 'https://models.inference.ai.azure.com',
    requiresToken: true,
    category: 'Pro',
    shortName: 'GPT-4o',
  },
  {
    id: 'gemma4',
    name: 'Gemma 4 (Local)',
    icon: '🔥',
    description: 'High-performance open model from Google',
    provider: 'ollama',
    baseUrl: '/api/ollama',
    requiresToken: false,
    category: 'Pro',
    shortName: 'Gemma 4',
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    icon: '✨',
    description: "Google's fast multimodal model",
    provider: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    requiresToken: true,
    category: 'Pro',
    shortName: 'Gemini',
  },
];
