import { createIntl, createIntlCache } from 'react-intl';

// Mock translations database
const translations: Record<string, Record<string, any>> = {
  en: {
    onboarding: {
      stepOf: ({ current, total }: { current: number; total: number }) => `Step ${current} of ${total}`,
      step1Title: ({ name }: { name: string }) => `Welcome, ${name}!`,
      step1Subtitle: 'Get started with Allerac One',
      step1Bullet1: 'Private & self-hosted',
      step1Bullet2: 'Local LLM support',
      step1Bullet3: 'Cross-conversation memory',
      letsGo: "Let's go",
      skipSetup: 'Skip setup',
      step2Title: 'Connect an AI Model',
      step2Subtitle: 'Choose your LLM provider',
      step2Instructions: 'Get a free API key from Google AI Studio',
      openStudio: 'Open Google AI Studio',
      pasteKeyLabel: 'Paste your API Key',
      keyPlaceholder: 'AIza...',
      keySaved: 'Saved',
      orDivider: 'Or',
      haveGithubToken: 'I have a GitHub token',
      useOllama: 'Use Ollama locally',
      githubTokenLabel: 'GitHub Token',
      githubTokenPlaceholder: 'ghp_...',
      step2PrivacyNote: 'Your keys are encrypted and stored securely.',
      back: 'Back',
      next: 'Next',
      step3Title: 'Tell us about yourself',
      step3Subtitle: 'Customize your AI assistant',
      step3LocationLabel: 'Location (optional)',
      step3LocationPlaceholder: 'San Francisco, CA',
      step3InstructionsLabel: 'System Instructions',
      step3Placeholder: 'Tell the AI about your role, expertise...',
      skipStep: 'Skip',
      saveAndNext: 'Save & Continue',
      step4Title: ({ name }: { name: string }) => `You're all set, ${name}!`,
      step4ConfiguredWith: 'Configured with:',
      step4Gemini: 'Google Gemini',
      step4Github: 'GitHub Models',
      step4Ollama: 'Ollama (local)',
      step4AboutMe: 'System Instructions',
      step4TipsTitle: 'Pro tips:',
      step4Tip1: 'You can change settings anytime',
      step4Tip2: 'Use system instructions to customize behavior',
      step4Tip3: 'Enable memory for cross-conversation learning',
      startChatting: 'Start Chatting',
      ollamaConnected: 'Ollama is connected',
      ollamaNotConnected: 'Ollama is not connected',
    },
    chat: {
      typeMessage: 'Type a message...',
      addAttachment: 'Add attachment',
      image: 'Image',
      document: 'Document',
      ollamaNotConnected: 'Ollama is not connected',
      googleNotConfigured: 'Google API key not configured',
      githubNotConfigured: 'GitHub token not configured',
    },
  },
  pt: {
    onboarding: {
      stepOf: ({ current, total }: { current: number; total: number }) => `Passo ${current} de ${total}`,
      step1Title: ({ name }: { name: string }) => `Bem-vindo, ${name}!`,
      step1Subtitle: 'Comece com Allerac One',
      step1Bullet1: 'Privado e auto-hospedado',
      step1Bullet2: 'Suporte a modelos LLM locais',
      step1Bullet3: 'Memória entre conversas',
      letsGo: "Vamos lá",
      skipSetup: 'Pular configuração',
      step2Title: 'Conecte um modelo de IA',
      step2Subtitle: 'Escolha seu provedor de LLM',
      step2Instructions: 'Obtenha uma chave de API grátis do Google AI Studio',
      openStudio: 'Abrir Google AI Studio',
      pasteKeyLabel: 'Cole sua chave de API',
      keyPlaceholder: 'AIza...',
      keySaved: 'Salvo',
      orDivider: 'Ou',
      haveGithubToken: 'Tenho um token do GitHub',
      useOllama: 'Usar Ollama localmente',
      githubTokenLabel: 'Token do GitHub',
      githubTokenPlaceholder: 'ghp_...',
      step2PrivacyNote: 'Suas chaves são criptografadas e armazenadas com segurança.',
      back: 'Voltar',
      next: 'Próximo',
      step3Title: 'Conte-nos sobre você',
      step3Subtitle: 'Personalize seu assistente de IA',
      step3LocationLabel: 'Localização (opcional)',
      step3LocationPlaceholder: 'São Paulo, SP',
      step3InstructionsLabel: 'Instruções do Sistema',
      step3Placeholder: 'Diga à IA sobre seu papel, experiência...',
      skipStep: 'Pular',
      saveAndNext: 'Salvar e Continuar',
      step4Title: ({ name }: { name: string }) => `Tudo pronto, ${name}!`,
      step4ConfiguredWith: 'Configurado com:',
      step4Gemini: 'Google Gemini',
      step4Github: 'GitHub Models',
      step4Ollama: 'Ollama (local)',
      step4AboutMe: 'Instruções do Sistema',
      step4TipsTitle: 'Dicas profissionais:',
      step4Tip1: 'Você pode alterar configurações a qualquer momento',
      step4Tip2: 'Use instruções do sistema para personalizar o comportamento',
      step4Tip3: 'Habilite memória para aprendizado entre conversas',
      startChatting: 'Começar a Conversar',
      ollamaConnected: 'Ollama está conectado',
      ollamaNotConnected: 'Ollama não está conectado',
    },
    chat: {
      typeMessage: 'Digite uma mensagem...',
      addAttachment: 'Adicionar anexo',
      image: 'Imagem',
      document: 'Documento',
      ollamaNotConnected: 'Ollama não está conectado',
      googleNotConfigured: 'Chave de API do Google não configurada',
      githubNotConfigured: 'Token do GitHub não configurado',
    },
  },
  es: {
    onboarding: {
      stepOf: ({ current, total }: { current: number; total: number }) => `Paso ${current} de ${total}`,
      step1Title: ({ name }: { name: string }) => `¡Bienvenido, ${name}!`,
      step1Subtitle: 'Comience con Allerac One',
      step1Bullet1: 'Privado y autohospedado',
      step1Bullet2: 'Soporte para modelos LLM locales',
      step1Bullet3: 'Memoria entre conversaciones',
      letsGo: 'Vamos',
      skipSetup: 'Omitir configuración',
      step2Title: 'Conecte un modelo de IA',
      step2Subtitle: 'Elija su proveedor de LLM',
      step2Instructions: 'Obtenga una clave de API gratuita de Google AI Studio',
      openStudio: 'Abrir Google AI Studio',
      pasteKeyLabel: 'Pegue su clave de API',
      keyPlaceholder: 'AIza...',
      keySaved: 'Guardado',
      orDivider: 'O',
      haveGithubToken: 'Tengo un token de GitHub',
      useOllama: 'Usar Ollama localmente',
      githubTokenLabel: 'Token de GitHub',
      githubTokenPlaceholder: 'ghp_...',
      step2PrivacyNote: 'Sus claves se cifran y almacenan de forma segura.',
      back: 'Atrás',
      next: 'Siguiente',
      step3Title: 'Cuéntenos sobre usted',
      step3Subtitle: 'Personalice su asistente de IA',
      step3LocationLabel: 'Ubicación (opcional)',
      step3LocationPlaceholder: 'Madrid, España',
      step3InstructionsLabel: 'Instrucciones del Sistema',
      step3Placeholder: 'Cuéntele a la IA sobre su función, experiencia...',
      skipStep: 'Omitir',
      saveAndNext: 'Guardar y Continuar',
      step4Title: ({ name }: { name: string }) => `¡Todo listo, ${name}!`,
      step4ConfiguredWith: 'Configurado con:',
      step4Gemini: 'Google Gemini',
      step4Github: 'GitHub Models',
      step4Ollama: 'Ollama (local)',
      step4AboutMe: 'Instrucciones del Sistema',
      step4TipsTitle: 'Consejos profesionales:',
      step4Tip1: 'Puede cambiar la configuración en cualquier momento',
      step4Tip2: 'Use instrucciones del sistema para personalizar el comportamiento',
      step4Tip3: 'Habilite la memoria para el aprendizaje entre conversaciones',
      startChatting: 'Comenzar a Chatear',
      ollamaConnected: 'Ollama está conectado',
      ollamaNotConnected: 'Ollama no está conectado',
    },
    chat: {
      typeMessage: 'Escriba un mensaje...',
      addAttachment: 'Agregar adjunto',
      image: 'Imagen',
      document: 'Documento',
      ollamaNotConnected: 'Ollama no está conectado',
      googleNotConfigured: 'Clave de API de Google no configurada',
      githubNotConfigured: 'Token de GitHub no configurado',
    },
  },
};

// Mock useTranslations hook
export function useTranslations(namespace?: string) {
  const locale = 'en';
  const ns = namespace || 'common';
  const messages = translations[locale]?.[ns] || {};

  return (key: string, params?: Record<string, any>) => {
    const value = messages[key];
    if (!value) return key;
    if (typeof value === 'function') return value(params || {});
    return value;
  };
}

// Mock useLocale hook
export function useLocale() {
  return 'en';
}
